[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
colabio = "2QkJLTKTtYFHS6xir1TEXLSdajM7r1Djf96JogKnRGSR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
rpc_url = "https://solana-api.projectserum.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test]
startup_wait = 20000 # Wait 20 seconds (20000 milliseconds)
# Optionally, uncomment to shut down validator after test
shutdown_wait = 2000