[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
colabio = "871mFBQrG5nUgZppc6BmdNnFmYvDRu6ixEQhKwfSS95j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test]
startup_wait = 20000 # Wait 20 seconds (20000 milliseconds)
# Optionally, uncomment to shut down validator after test
shutdown_wait = 2000